# Generated by Django 4.2.6 on 2023-10-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0003_alter_osoba_plec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
    ]
