# Generated by Django 4.2.6 on 2023-11-23 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0007_osoba_wlasciciel_alter_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('can_view_other_persons', 'pozwala na wyswietlanie obiektow Osoba ktorych zalogowany uzytkownik nie jest wlascicielem')]},
        ),
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(default=datetime.date(2023, 11, 23)),
        ),
    ]
