# Generated by Django 4.2.6 on 2023-12-05 18:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wwwapp', '0008_alter_osoba_options_alter_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(default=datetime.date(2023, 12, 5)),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='stanowisko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wwwapp.stanowisko'),
        ),
    ]
